name: cpdn_cli
description: A sample command-line application.
version: 1.0.1
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  ansicolor: ^1.0.2
  process_run: ^0.10.12+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  arctekko: main